name: Publish release to Nuget registry

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check github.ref starts with 'refs/tags/'
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: |
          echo Error! github.ref does not start with 'refs/tags'
          echo github.ref: ${{ github.ref }}
          exit 1
      - name: Set release version number
        env:
          github_ref: ${{ github.ref }}
        run: |
          version="${github_ref:10}"
          echo version=$version
          echo "version=$version" >> $GITHUB_ENV
      - name: Use .NET Core 3.1 SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
          source-url: https://api.nuget.org/v3/index.json
        # Error: The NUGET_AUTH_TOKEN environment variable was not provided. In this step, add the following: 
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}
      - name: Install dependencies
        working-directory: src
        run: dotnet restore
        env:
          DOTNET_NOLOGO: true
          DOTNET_CLI_TELEMETRY_OPTOUT: true
      - name: Build solution [Release]
        working-directory: src
        run: dotnet build --no-restore -c Release -p:Version=$version
      - name: Pack solution [Release]
        working-directory: src
        run: dotnet pack --no-restore -c Release -p:Version=$version -o out
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Nuget packages
          path: |
            src/out/*
      - name: Publish Nuget packages to Nuget registry
        working-directory: src
        run: dotnet nuget push "out/*" -k ${{secrets.NUGET_API_KEY}}
